# service:
    # Container Info
      # image: 
      # container_name:
      # restart:
      # depends_on:
    # Resources
      # deploy:
      # devices:
      # volumes:
      # ports:
    # Validation
      # healthcheck
    # Configuration
      # command
      # environment:

services:
  homepage:
    # Container Info
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    # Resources
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    volumes:
      - ${CONFIG_PATH}/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3000:3000
    # Configuration
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 192.168.42.34:3000,home.home.lab,homelab.home.lab,homepage.home.lab
      HOMEPAGE_VAR_UPTIME_KUMA_API_KEY: ${UPTIME_KUMA_API_KEY}
      HOMEPAGE_VAR_PIHOLE_API_KEY: ${PIHOLE_API_KEY}
      HOMEPAGE_VAR_PROXMOX_API_KEY: ${PROXMOX_API_KEY}
      HOMEPAGE_VAR_JELLYFIN_API_KEY: ${JELLYFIN_API_KEY}
      HOMEPAGE_VAR_QBITTORRENT_PASS: ${QBITTORRENT_PASS}
      HOMEPAGE_VAR_SEERR_API_KEY: ${SEERR_API_KEY}
      HOMEPAGE_VAR_PROWLARR_API_KEY: ${PROWLARR_API_KEY}
      HOMEPAGE_VAR_SONARR_API_KEY: ${SONARR_API_KEY}
      HOMEPAGE_VAR_RADARR_API_KEY: ${RADARR_API_KEY}
      HOMEPAGE_VAR_HA_LONG_LIVED_TOKEN: ${HA_LONG_LIVED_TOKEN}

  uptime-kuma:
    # Container Info
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    # Resources
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    volumes:
      - ${CONFIG_PATH}/uptime-kuma/data:/app/data
    ports:
      - 3001:3001
    # Configuration

  ntfy:
    # Container Info
    image: binwiederhier/ntfy
    container_name: ntfy
    restart: unless-stopped
    # Resources
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
    volumes:
      - ${CONFIG_PATH}/ntfy/cache:/var/cache/ntfy
      - ${CONFIG_PATH}/ntfy/etc:/etc/ntfy
      - ${CONFIG_PATH}/ntfy/attachments:/var/cache/ntfy/attachments
    ports:
      - 80:80
    # Validation
    init: true #Required for health check
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Configuration
    command: serve
    environment:
      NTFY_BASE_URL: "https://ntfy.home.lab"
      NTFY_BEHIND_PROXY: "true"
      NTFY_ATTACHMENT_CACHE_DIR: "/var/cache/ntfy/attachments"
      NTFY_CACHE_FILE: "/var/cache/ntfy/cache.db"

  diun:
    # Container Info
    image: crazymax/diun:latest
    container_name: diun
    restart: unless-stopped
    # Resources
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
    volumes:
      - ${CONFIG_PATH}/diun/data:/data
      - ${CONFIG_PATH}/diun/diun.yml:/etc/diun/diun.yml
    # Validation
    healthcheck:
      test: ["CMD", "diun", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    # Configuration
    command: serve
    environment:
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"

  beszel:
    # Container Info
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    # Resources
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    volumes:
      - ${CONFIG_PATH}/beszel/data:/beszel_data
      - ${CONFIG_PATH}/beszel/socket:/beszel_socket
    ports:
      - 8090:8090
    # Validation
    healthcheck:
      test: ['CMD', '/beszel', 'health', '--url', 'http://localhost:8090']
      interval: 120s
      start_period: 10s
      timeout: 5s

  pulse:
    # Container Info
    image: rcourtman/pulse:latest
    container_name: pulse
    restart: unless-stopped
    # Resources
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 768M
    volumes:
      - ${CONFIG_PATH}/pulse/data:/data
    ports:
      - 7655:7655
    # Configuration
    environment:
      - PULSE_DEPLOYMENT_METHOD=docker_compose

  # ntfy-adapter:
    # Container Info
  #   image: ghcr.io/chr0nzz/ntfy-adapter:latest
  #   container_name: ntfy-adapter
  #   restart: unless-stopped
  #   depends_on:
  #     - ntfy
    # Resources
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.25"
  #         memory: 128M
  #   volumes:
  #     - ./ntfy-adapter/cache:/var/cache/ntfy
  #   ports:
  #     - 5000:5000
    # Configuration
  #   environment:
  #     - NTFY_URL=http://ntfy:80
  #     - TZ=America/Chicago
  #     - EXPIRY_MAX=24
  #     - EXPIRY_HIGH=12
  #     - EXPIRY_STANDARD=6
  #     - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
  #     - NTFY_CACHE_DURATION=48h
